Update make

diff --git a/router/phicomm_n1/make b/router/phicomm_n1/make
--- a/router/phicomm_n1/make
+++ b/router/phicomm_n1/make
@@ -65,7 +65,9 @@ extract_openwrt() {
         img)
             loop_setup $firmware
             if ! mount -r ${loop}p2 $mount; then
-                die "mount ${loop}p2 failed!"
+                if ! mount -r ${loop}p1 $mount; then
+                    die "mount ${loop} failed!"
+                fi
             fi
             cp -r $mount/* $root_comm && sync
             umount -f $mount
@@ -116,6 +118,9 @@ utils() {
         echo 'pwm_meson' > etc/modules.d/pwm-meson
         if ! grep -q 'ulimit -n' etc/init.d/boot; then
             sed -i '/kmodloader/i \\tulimit -n 51200\n' etc/init.d/boot
+        fi
+        if ! grep -q '/tmp/upgrade' etc/init.d/boot; then
+            sed -i '/mkdir -p \/tmp\/.uci/a \\tmkdir -p \/tmp\/upgrade' etc/init.d/boot
         fi
         sed -i 's/ttyAMA0/ttyAML0/' etc/inittab
         sed -i 's/ttyS0/tty0/' etc/inittab
