Update n1-install

diff --git a/router/phicomm_n1/install-program/files/n1-install b/router/phicomm_n1/install-program/files/n1-install
--- a/router/phicomm_n1/install-program/files/n1-install
+++ b/router/phicomm_n1/install-program/files/n1-install
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 die() {
-    echo -e "\033[31mError:\033[0m $1" && exit 1
+    echo -e "\033[31m Error:\033[0m $1" && exit 1
 }
 
 emmc=$(lsblk | grep -oE 'mmcblk[0-9]' | sort | uniq)
@@ -10,57 +10,55 @@ sd=$(lsblk | grep -oE 'sd[a-z]' | sort | uniq)
 [ "$emmc" ] || die "no emmc found!!"
 [ "$sd" ] || die "no usb device found!!"
 
-sd=$(lsblk | grep -w '/' | grep -oE 'sd[a-z]')
+sd=$(lsblk | grep -w -E '/|/overlay' | grep -oE 'sd[a-z]')
 [ "$sd" ] || die "you are running in emmc mode, please boot system with usb!!"
 
 dev_emmc="/dev/$emmc"
 dev_sd="/dev/$sd"
 
-echo "emmc: $dev_emmc"
-echo "usb:  $dev_sd"
+echo " emmc: $dev_emmc"
+echo " usb:  $dev_sd"
+
+if (blkid -L "BOOT_EMMC" && blkid -L "ROOT_EMMC") >/dev/null 2>&1; then
+    installed=true
+fi
+
+if grep -q $dev_emmc /proc/mounts; then
+    echo " umount emmc..."
+    umount -f ${dev_emmc}p* >/dev/null 2>&1
+fi
 
 part_boot="${dev_emmc}p1"
 part_root="${dev_emmc}p2"
-part_data="${dev_emmc}p3"
 
-if grep -q $dev_emmc /proc/mounts; then
-    echo "umount emmc..."
-    umount -f ${dev_emmc}p* 2>/dev/null
-fi
+if [ ! $installed ]; then
+    parted -v >/dev/null 2>&1 || die "package parted not found!!"
 
-if [ $(blkid | grep -E 'BOOT_EMMC|ROOT_EMMC|DATA' | wc -l) != 3 ]; then
-    # parted -v >/dev/null 2>&1 || die "package parted not found!!"
+    echo " backup u-boot..."
+    dd if=$dev_emmc of=u-boot.img bs=1M count=4
 
-    echo "backup u-boot..."
-    dd if=$dev_emmc of=u-boot.img bs=1M count=4 2>/dev/null
-
-    echo "create mbr and partition..."
+    echo " create mbr and partition..."
     parted -s $dev_emmc mklabel msdos
-    parted -s $dev_emmc mkpart primary fat32 700M 956M
-    parted -s $dev_emmc mkpart primary ext4 957M 1981M
-    parted -s $dev_emmc mkpart primary ext4 1982M 100%
+    parted -s $dev_emmc mkpart primary fat32 700M 1212M
+    parted -s $dev_emmc mkpart primary ext4 1213M 100%
 
-    echo "restore u-boot..."
-    dd if=u-boot.img of=$dev_emmc conv=fsync bs=1 count=442 2>/dev/null
-    dd if=u-boot.img of=$dev_emmc conv=fsync bs=512 skip=1 seek=1 2>/dev/null
+    echo " restore u-boot..."
+    dd if=u-boot.img of=$dev_emmc conv=fsync bs=1 count=442
+    dd if=u-boot.img of=$dev_emmc conv=fsync bs=512 skip=1 seek=1
 
     sync
 
     if grep -q $dev_emmc /proc/mounts; then
-        # echo "umount emmc..."
-        umount -f ${dev_emmc}p* 2>/dev/null
+        echo " umount emmc..."
+        umount -f ${dev_emmc}p* >/dev/null 2>&1
     fi
+    
+    echo " format boot partiton..."
+    mkfs.fat -F 32 -n "BOOT_EMMC" $part_boot
 
-    echo "format boot partiton..."
-    mkfs.fat -F 32 -n "BOOT_EMMC" $part_boot >/dev/null
-
-    echo "format root partiton..."
-    mke2fs -t ext4 -F -q -L "ROOT_EMMC" -m 0 $part_root >/dev/null
+    echo " format root partiton..."
+    mke2fs -t ext4 -F -q -L "ROOT_EMMC" -m 0 $part_root
     e2fsck -n $part_root
-
-    echo "format data partiton..."
-    mke2fs -t ext4 -F -q -L "DATA" -m 0 $part_data >/dev/null
-    e2fsck -n $part_data
 fi
 
 ins_boot="/install/boot"
@@ -68,18 +66,18 @@ ins_root="/install/root"
 
 mkdir -p -m 777 $ins_boot $ins_root
 
-echo "mount bootfs..."
+echo " mount bootfs..."
 mount -t vfat $part_boot $ins_boot
 rm -rf $ins_boot/*
 
-echo "copy bootable file..."
-grep -w -q '/boot' /proc/mounts || mount -t vfat ${dev_sd}1 /boot
+echo " copy bootable file..."
+lsblk | grep -w -q '/boot' || mount -t vfat ${dev_sd}1 /boot
 rm -rf /boot/'System Volume Information'
 cp -r /boot/* $ins_boot
 sync
 
-echo "edit uEnv..."
-uuid=$(blkid $(blkid -L "ROOT_EMMC") | awk '{ print $3 }' | cut -d '"' -f 2)
+echo " edit uEnv.txt..."
+uuid=$(blkid `blkid -L "ROOT_EMMC"` | awk '{ print $3 }' | cut -d '"' -f 2)
 if [ $uuid ]; then
     sed -i "s/LABEL=ROOTFS/UUID=$uuid/" $ins_boot/uEnv.txt
 else
@@ -91,30 +89,30 @@ rm -f $ins_boot/aml*
 rm -f $ins_boot/boot.ini
 mv -f $ins_boot/boot-emmc.scr $ins_boot/boot.scr
 
-echo "umount bootfs..."
+echo " umount bootfs..."
 umount -f $part_boot
 
-echo "mount rootfs..."
+echo " mount rootfs..."
 mount -t ext4 $part_root $ins_root
 rm -rf $ins_root/*
 
-echo "copy rootfs..."
+echo " copy rootfs..."
 
 cd /
 echo "  --> copy bin..."
-tar -cf - bin | (cd $ins_root; tar -xpf -)
+tar -cf - bin | (cd $ins_root && tar -xpf -)
 echo "  --> copy etc..."
-tar -cf - etc | (cd $ins_root; tar -xpf -)
+tar -cf - etc | (cd $ins_root && tar -xpf -)
 echo "  --> copy lib..."
-tar -cf - lib | (cd $ins_root; tar -xpf -)
+tar -cf - lib | (cd $ins_root && tar -xpf -)
 echo "  --> copy root..."
-tar -cf - root | (cd $ins_root; tar -xpf -)
+tar -cf - root | (cd $ins_root && tar -xpf -)
 echo "  --> copy sbin..."
-tar -cf - sbin | (cd $ins_root; tar -xpf -)
+tar -cf - sbin | (cd $ins_root && tar -xpf -)
 echo "  --> copy usr..."
-tar -cf - usr | (cd $ins_root; tar -xpf -)
+tar -cf - usr | (cd $ins_root && tar -xpf -)
 echo "  --> copy www..."
-tar -cf - www | (cd $ins_root; tar -xpf -)
+tar -cf - www | (cd $ins_root && tar -xpf -)
 
 [ -f init ] && cp -f init $ins_root
 
@@ -126,7 +124,7 @@ ln -sf lib lib64
 echo "  --> link var..."
 ln -sf tmp var
 
-echo "edit fstab..."
+echo " edit fstab..."
 sed -i "s/'BOOT'/'BOOT_EMMC'/" etc/config/fstab
 if [ $uuid ]; then
     sed -i -e '/ROOTFS/ s/label/uuid/' etc/config/fstab
@@ -137,13 +135,13 @@ fi
 
 rm -f usr/bin/n1-install
 
-echo "sync..."
+echo " sync..."
 cd /
 sync
 
-echo "umount rootfs..."
+echo " umount rootfs..."
 umount -f $part_root
 
 rm -rf install
 
-echo "copy openwrt os to emmc done!"
+echo " copy openwrt os to emmc done!"
